User can view specific product
Kiptong/Foodie-Swag pull request #7
Opened 2017-06-20 18:59 UTC by Kiptong

![issue-2 demo](https://user-images.githubusercontent.com/29046247/27350704-f0f2a182-55af-11e7-968b-5f72f2d4768b.gif)

2017-06-20 20:55 UTC, thebearingedge requested changes
- Make [select boxes](http://getbootstrap.com/css/#selects) match the rest of the bootstrap theme.
- Remove "Back to Products" button until it works.
Also, You

2017-06-21 02:31 UTC, thebearingedge requested changes

2017-06-21 02:31 UTC, thebearingedge commented on main.js
> +function btpFunc(event) {
Avoid abbreviations. What does this function do? Name it that.

2017-06-21 16:27 UTC, Kiptong commented on main.js
> +function btpFunc(event) {
Understood Tim, this should be good to go.

2017-06-21 16:29 UTC, thebearingedge approved these changes

2017-06-21 17:23 UTC, merged